/**
 * GENERATED FILE — do not edit.
 *
 * Source: ml/vocabulary.py
 * Regenerate: python ml/export_vocabulary.py
 *
 * The ISL vocabulary shared by the whole product: the glosses the recogniser can
 * predict, the English words that map onto each one, and the part of speech the
 * grammar engine in ./grammar.ts needs to order a sentence.
 */

export type PartOfSpeech =
  | "pronoun"
  | "noun"
  | "verb"
  | "adjective"
  | "adverb"
  | "time"
  | "question"
  | "number"
  | "response"
  | "greeting"
  | "quantifier";

export interface VocabularyEntry {
  gloss: string;
  /** Every English form that maps to this sign; the first is the preferred one. */
  surfaces: string[];
  pos: PartOfSpeech;
}

export const VOCABULARY: VocabularyEntry[] = [
  { gloss: "i", surfaces: ["i", "me", "my", "mine", "myself"], pos: "pronoun" },
  { gloss: "you", surfaces: ["you", "your", "yours", "yourself"], pos: "pronoun" },
  { gloss: "he", surfaces: ["he", "him", "his"], pos: "pronoun" },
  { gloss: "she", surfaces: ["she", "her", "hers"], pos: "pronoun" },
  { gloss: "we", surfaces: ["we", "us", "our", "ours"], pos: "pronoun" },
  { gloss: "they", surfaces: ["they", "them", "their", "theirs"], pos: "pronoun" },
  { gloss: "this", surfaces: ["this"], pos: "pronoun" },
  { gloss: "that", surfaces: ["that"], pos: "pronoun" },
  { gloss: "what", surfaces: ["what"], pos: "question" },
  { gloss: "where", surfaces: ["where"], pos: "question" },
  { gloss: "who", surfaces: ["who", "whom"], pos: "question" },
  { gloss: "when", surfaces: ["when"], pos: "question" },
  { gloss: "why", surfaces: ["why"], pos: "question" },
  { gloss: "how", surfaces: ["how"], pos: "question" },
  { gloss: "howmany", surfaces: ["how many"], pos: "question" },
  { gloss: "howmuch", surfaces: ["how much"], pos: "question" },
  { gloss: "which", surfaces: ["which"], pos: "question" },
  { gloss: "yes", surfaces: ["yes", "yeah", "yep", "correct", "right"], pos: "response" },
  { gloss: "no", surfaces: ["no", "nope", "not"], pos: "response" },
  { gloss: "maybe", surfaces: ["maybe", "perhaps"], pos: "response" },
  { gloss: "please", surfaces: ["please"], pos: "response" },
  { gloss: "sorry", surfaces: ["sorry", "apologise", "apologize", "excuse me"], pos: "response" },
  { gloss: "thankyou", surfaces: ["thank you", "thanks", "thank"], pos: "response" },
  { gloss: "ok", surfaces: ["ok", "okay", "fine", "alright"], pos: "response" },
  { gloss: "hello", surfaces: ["hello", "hi", "hey"], pos: "greeting" },
  { gloss: "goodbye", surfaces: ["goodbye", "bye", "see you"], pos: "greeting" },
  { gloss: "goodmorning", surfaces: ["good morning"], pos: "greeting" },
  { gloss: "goodafternoon", surfaces: ["good afternoon"], pos: "greeting" },
  { gloss: "goodevening", surfaces: ["good evening"], pos: "greeting" },
  { gloss: "goodnight", surfaces: ["good night"], pos: "greeting" },
  { gloss: "howareyou", surfaces: ["how are you", "how do you do"], pos: "greeting" },
  { gloss: "welcome", surfaces: ["welcome"], pos: "greeting" },
  { gloss: "pleased", surfaces: ["pleased", "nice to meet you", "glad"], pos: "greeting" },
  { gloss: "eat", surfaces: ["eat", "eating", "ate"], pos: "verb" },
  { gloss: "drink", surfaces: ["drink", "drinking", "drank"], pos: "verb" },
  { gloss: "help", surfaces: ["help", "helping", "assist", "assistance"], pos: "verb" },
  { gloss: "want", surfaces: ["want", "wants", "wanted", "would like"], pos: "verb" },
  { gloss: "need", surfaces: ["need", "needs", "needed", "require"], pos: "verb" },
  { gloss: "have", surfaces: ["have", "has", "had"], pos: "verb" },
  { gloss: "give", surfaces: ["give", "gives", "gave", "hand over"], pos: "verb" },
  { gloss: "take", surfaces: ["take", "takes", "took"], pos: "verb" },
  { gloss: "go", surfaces: ["go", "goes", "went", "leave"], pos: "verb" },
  { gloss: "come", surfaces: ["come", "comes", "came", "arrive"], pos: "verb" },
  { gloss: "sit", surfaces: ["sit", "sits", "sat", "sit down"], pos: "verb" },
  { gloss: "stand", surfaces: ["stand", "stands", "stood", "stand up"], pos: "verb" },
  { gloss: "walk", surfaces: ["walk", "walks", "walking"], pos: "verb" },
  { gloss: "stop", surfaces: ["stop", "stops", "stopped", "halt"], pos: "verb" },
  { gloss: "wait", surfaces: ["wait", "waits", "waiting"], pos: "verb" },
  { gloss: "sleep", surfaces: ["sleep", "sleeps", "slept", "asleep"], pos: "verb" },
  { gloss: "wakeup", surfaces: ["wake up", "wake", "woke"], pos: "verb" },
  { gloss: "work", surfaces: ["work", "works", "working", "job"], pos: "verb" },
  { gloss: "study", surfaces: ["study", "studies", "studying"], pos: "verb" },
  { gloss: "learn", surfaces: ["learn", "learns", "learning", "learnt"], pos: "verb" },
  { gloss: "teach", surfaces: ["teach", "teaches", "taught"], pos: "verb" },
  { gloss: "read", surfaces: ["read", "reads", "reading"], pos: "verb" },
  { gloss: "write", surfaces: ["write", "writes", "wrote", "writing"], pos: "verb" },
  { gloss: "speak", surfaces: ["speak", "speaks", "talk", "talks", "say", "tell"], pos: "verb" },
  { gloss: "listen", surfaces: ["listen", "listens", "hear", "hears"], pos: "verb" },
  { gloss: "see", surfaces: ["see", "sees", "saw", "look", "watch"], pos: "verb" },
  { gloss: "understand", surfaces: ["understand", "understands", "understood"], pos: "verb" },
  { gloss: "know", surfaces: ["know", "knows", "knew"], pos: "verb" },
  { gloss: "dontknow", surfaces: ["don't know", "do not know", "dunno"], pos: "verb" },
  { gloss: "think", surfaces: ["think", "thinks", "thought"], pos: "verb" },
  { gloss: "remember", surfaces: ["remember", "remembers", "recall"], pos: "verb" },
  { gloss: "forget", surfaces: ["forget", "forgets", "forgot"], pos: "verb" },
  { gloss: "like", surfaces: ["like", "likes", "liked", "enjoy"], pos: "verb" },
  { gloss: "love", surfaces: ["love", "loves", "loved"], pos: "verb" },
  { gloss: "ask", surfaces: ["ask", "asks", "asked", "question"], pos: "verb" },
  { gloss: "answer", surfaces: ["answer", "answers", "reply"], pos: "verb" },
  { gloss: "buy", surfaces: ["buy", "buys", "bought", "purchase"], pos: "verb" },
  { gloss: "sell", surfaces: ["sell", "sells", "sold"], pos: "verb" },
  { gloss: "pay", surfaces: ["pay", "pays", "paid", "payment"], pos: "verb" },
  { gloss: "open", surfaces: ["open", "opens", "opened"], pos: "verb" },
  { gloss: "close", surfaces: ["close", "closes", "closed", "shut"], pos: "verb" },
  { gloss: "wash", surfaces: ["wash", "washes", "washed"], pos: "verb" },
  { gloss: "cook", surfaces: ["cook", "cooks", "cooking"], pos: "verb" },
  { gloss: "call", surfaces: ["call", "calls", "called", "phone"], pos: "verb" },
  { gloss: "meet", surfaces: ["meet", "meets", "met"], pos: "verb" },
  { gloss: "live", surfaces: ["live", "lives", "lived", "stay"], pos: "verb" },
  { gloss: "play", surfaces: ["play", "plays", "played", "game"], pos: "verb" },
  { gloss: "drive", surfaces: ["drive", "drives", "drove", "driving"], pos: "verb" },
  { gloss: "send", surfaces: ["send", "sends", "sent"], pos: "verb" },
  { gloss: "bring", surfaces: ["bring", "brings", "brought"], pos: "verb" },
  { gloss: "find", surfaces: ["find", "finds", "found"], pos: "verb" },
  { gloss: "lose", surfaces: ["lose", "loses", "lost"], pos: "verb" },
  { gloss: "wear", surfaces: ["wear", "wears", "wore", "dress"], pos: "verb" },
  { gloss: "show", surfaces: ["show", "shows", "showed"], pos: "verb" },
  { gloss: "start", surfaces: ["start", "starts", "started", "begin"], pos: "verb" },
  { gloss: "finish", surfaces: ["finish", "finished", "done", "complete"], pos: "verb" },
  { gloss: "can", surfaces: ["can", "able", "possible"], pos: "verb" },
  { gloss: "cannot", surfaces: ["cannot", "can't", "unable", "impossible"], pos: "verb" },
  { gloss: "pain", surfaces: ["pain", "hurt", "hurts", "ache", "sore"], pos: "noun" },
  { gloss: "sick", surfaces: ["sick", "ill", "unwell"], pos: "adjective" },
  { gloss: "doctor", surfaces: ["doctor", "physician"], pos: "noun" },
  { gloss: "nurse", surfaces: ["nurse"], pos: "noun" },
  { gloss: "hospital", surfaces: ["hospital", "clinic"], pos: "noun" },
  { gloss: "medicine", surfaces: ["medicine", "medication", "drug"], pos: "noun" },
  { gloss: "tablet", surfaces: ["tablet", "pill"], pos: "noun" },
  { gloss: "injection", surfaces: ["injection", "shot", "jab"], pos: "noun" },
  { gloss: "fever", surfaces: ["fever", "temperature"], pos: "noun" },
  { gloss: "cough", surfaces: ["cough", "coughing"], pos: "noun" },
  { gloss: "headache", surfaces: ["headache"], pos: "noun" },
  { gloss: "stomach", surfaces: ["stomach", "belly", "tummy"], pos: "noun" },
  { gloss: "blood", surfaces: ["blood"], pos: "noun" },
  { gloss: "operation", surfaces: ["operation", "surgery"], pos: "noun" },
  { gloss: "ambulance", surfaces: ["ambulance"], pos: "noun" },
  { gloss: "police", surfaces: ["police", "policeman", "cop"], pos: "noun" },
  { gloss: "fire", surfaces: ["fire"], pos: "noun" },
  { gloss: "emergency", surfaces: ["emergency", "urgent"], pos: "noun" },
  { gloss: "accident", surfaces: ["accident", "crash"], pos: "noun" },
  { gloss: "danger", surfaces: ["danger", "dangerous", "unsafe"], pos: "adjective" },
  { gloss: "careful", surfaces: ["careful", "carefully", "caution"], pos: "adjective" },
  { gloss: "deaf", surfaces: ["deaf", "hard of hearing"], pos: "adjective" },
  { gloss: "blind", surfaces: ["blind"], pos: "adjective" },
  { gloss: "hearingaid", surfaces: ["hearing aid"], pos: "noun" },
  { gloss: "signlanguage", surfaces: ["sign language", "isl"], pos: "noun" },
  { gloss: "interpreter", surfaces: ["interpreter", "translator"], pos: "noun" },
  { gloss: "mother", surfaces: ["mother", "mom", "mum", "mummy"], pos: "noun" },
  { gloss: "father", surfaces: ["father", "dad", "papa"], pos: "noun" },
  { gloss: "brother", surfaces: ["brother"], pos: "noun" },
  { gloss: "sister", surfaces: ["sister"], pos: "noun" },
  { gloss: "son", surfaces: ["son"], pos: "noun" },
  { gloss: "daughter", surfaces: ["daughter"], pos: "noun" },
  { gloss: "wife", surfaces: ["wife"], pos: "noun" },
  { gloss: "husband", surfaces: ["husband"], pos: "noun" },
  { gloss: "family", surfaces: ["family"], pos: "noun" },
  { gloss: "friend", surfaces: ["friend", "friends"], pos: "noun" },
  { gloss: "baby", surfaces: ["baby", "infant"], pos: "noun" },
  { gloss: "child", surfaces: ["child", "kid", "children"], pos: "noun" },
  { gloss: "man", surfaces: ["man", "male", "gentleman"], pos: "noun" },
  { gloss: "woman", surfaces: ["woman", "female", "lady"], pos: "noun" },
  { gloss: "boy", surfaces: ["boy"], pos: "noun" },
  { gloss: "girl", surfaces: ["girl"], pos: "noun" },
  { gloss: "people", surfaces: ["people", "person", "everyone"], pos: "noun" },
  { gloss: "teacher", surfaces: ["teacher"], pos: "noun" },
  { gloss: "student", surfaces: ["student", "pupil"], pos: "noun" },
  { gloss: "name", surfaces: ["name", "named", "called"], pos: "noun" },
  { gloss: "home", surfaces: ["home", "house"], pos: "noun" },
  { gloss: "school", surfaces: ["school"], pos: "noun" },
  { gloss: "college", surfaces: ["college", "university"], pos: "noun" },
  { gloss: "office", surfaces: ["office"], pos: "noun" },
  { gloss: "shop", surfaces: ["shop", "store"], pos: "noun" },
  { gloss: "market", surfaces: ["market", "bazaar"], pos: "noun" },
  { gloss: "bank", surfaces: ["bank"], pos: "noun" },
  { gloss: "restaurant", surfaces: ["restaurant", "hotel", "cafe"], pos: "noun" },
  { gloss: "toilet", surfaces: ["toilet", "bathroom", "washroom", "restroom"], pos: "noun" },
  { gloss: "kitchen", surfaces: ["kitchen"], pos: "noun" },
  { gloss: "room", surfaces: ["room"], pos: "noun" },
  { gloss: "road", surfaces: ["road", "street"], pos: "noun" },
  { gloss: "station", surfaces: ["station"], pos: "noun" },
  { gloss: "city", surfaces: ["city", "town"], pos: "noun" },
  { gloss: "village", surfaces: ["village"], pos: "noun" },
  { gloss: "india", surfaces: ["india", "indian"], pos: "noun" },
  { gloss: "here", surfaces: ["here"], pos: "adverb" },
  { gloss: "there", surfaces: ["there"], pos: "adverb" },
  { gloss: "water", surfaces: ["water"], pos: "noun" },
  { gloss: "food", surfaces: ["food", "meal"], pos: "noun" },
  { gloss: "milk", surfaces: ["milk"], pos: "noun" },
  { gloss: "tea", surfaces: ["tea", "chai"], pos: "noun" },
  { gloss: "rice", surfaces: ["rice"], pos: "noun" },
  { gloss: "bread", surfaces: ["bread", "roti"], pos: "noun" },
  { gloss: "fruit", surfaces: ["fruit"], pos: "noun" },
  { gloss: "vegetable", surfaces: ["vegetable", "vegetables"], pos: "noun" },
  { gloss: "egg", surfaces: ["egg", "eggs"], pos: "noun" },
  { gloss: "salt", surfaces: ["salt"], pos: "noun" },
  { gloss: "sugar", surfaces: ["sugar"], pos: "noun" },
  { gloss: "hungry", surfaces: ["hungry", "hunger"], pos: "adjective" },
  { gloss: "thirsty", surfaces: ["thirsty", "thirst"], pos: "adjective" },
  { gloss: "money", surfaces: ["money", "cash", "rupees"], pos: "noun" },
  { gloss: "price", surfaces: ["price", "cost", "rate"], pos: "noun" },
  { gloss: "phone", surfaces: ["phone", "mobile", "cell phone", "telephone"], pos: "noun" },
  { gloss: "book", surfaces: ["book"], pos: "noun" },
  { gloss: "bag", surfaces: ["bag"], pos: "noun" },
  { gloss: "key", surfaces: ["key", "keys"], pos: "noun" },
  { gloss: "clothes", surfaces: ["clothes", "clothing"], pos: "noun" },
  { gloss: "car", surfaces: ["car"], pos: "noun" },
  { gloss: "bus", surfaces: ["bus"], pos: "noun" },
  { gloss: "train", surfaces: ["train"], pos: "noun" },
  { gloss: "ticket", surfaces: ["ticket"], pos: "noun" },
  { gloss: "today", surfaces: ["today"], pos: "time" },
  { gloss: "tomorrow", surfaces: ["tomorrow"], pos: "time" },
  { gloss: "yesterday", surfaces: ["yesterday"], pos: "time" },
  { gloss: "now", surfaces: ["now", "right now", "currently"], pos: "time" },
  { gloss: "later", surfaces: ["later", "afterwards"], pos: "time" },
  { gloss: "morning", surfaces: ["morning"], pos: "time" },
  { gloss: "afternoon", surfaces: ["afternoon"], pos: "time" },
  { gloss: "evening", surfaces: ["evening"], pos: "time" },
  { gloss: "night", surfaces: ["night", "tonight"], pos: "time" },
  { gloss: "day", surfaces: ["day"], pos: "time" },
  { gloss: "week", surfaces: ["week"], pos: "time" },
  { gloss: "month", surfaces: ["month"], pos: "time" },
  { gloss: "year", surfaces: ["year"], pos: "time" },
  { gloss: "time", surfaces: ["time", "o'clock"], pos: "time" },
  { gloss: "hour", surfaces: ["hour", "hours"], pos: "time" },
  { gloss: "minute", surfaces: ["minute", "minutes"], pos: "time" },
  { gloss: "early", surfaces: ["early"], pos: "time" },
  { gloss: "late", surfaces: ["late"], pos: "time" },
  { gloss: "always", surfaces: ["always"], pos: "adverb" },
  { gloss: "never", surfaces: ["never"], pos: "adverb" },
  { gloss: "sometimes", surfaces: ["sometimes"], pos: "adverb" },
  { gloss: "again", surfaces: ["again", "repeat", "once more"], pos: "adverb" },
  { gloss: "good", surfaces: ["good", "well", "nice"], pos: "adjective" },
  { gloss: "bad", surfaces: ["bad", "poor", "awful"], pos: "adjective" },
  { gloss: "happy", surfaces: ["happy", "glad", "joy"], pos: "adjective" },
  { gloss: "sad", surfaces: ["sad", "unhappy", "upset"], pos: "adjective" },
  { gloss: "angry", surfaces: ["angry", "anger", "mad"], pos: "adjective" },
  { gloss: "afraid", surfaces: ["afraid", "scared", "fear", "frightened"], pos: "adjective" },
  { gloss: "tired", surfaces: ["tired", "exhausted"], pos: "adjective" },
  { gloss: "hot", surfaces: ["hot", "warm"], pos: "adjective" },
  { gloss: "cold", surfaces: ["cold", "cool"], pos: "adjective" },
  { gloss: "big", surfaces: ["big", "large", "huge"], pos: "adjective" },
  { gloss: "small", surfaces: ["small", "little", "tiny"], pos: "adjective" },
  { gloss: "fast", surfaces: ["fast", "quick", "quickly"], pos: "adjective" },
  { gloss: "slow", surfaces: ["slow", "slowly"], pos: "adjective" },
  { gloss: "new", surfaces: ["new"], pos: "adjective" },
  { gloss: "old", surfaces: ["old"], pos: "adjective" },
  { gloss: "beautiful", surfaces: ["beautiful", "pretty", "lovely"], pos: "adjective" },
  { gloss: "difficult", surfaces: ["difficult", "hard", "tough"], pos: "adjective" },
  { gloss: "easy", surfaces: ["easy", "simple"], pos: "adjective" },
  { gloss: "important", surfaces: ["important"], pos: "adjective" },
  { gloss: "ready", surfaces: ["ready"], pos: "adjective" },
  { gloss: "busy", surfaces: ["busy"], pos: "adjective" },
  { gloss: "free", surfaces: ["free", "available"], pos: "adjective" },
  { gloss: "full", surfaces: ["full"], pos: "adjective" },
  { gloss: "empty", surfaces: ["empty"], pos: "adjective" },
  { gloss: "clean", surfaces: ["clean"], pos: "adjective" },
  { gloss: "dirty", surfaces: ["dirty"], pos: "adjective" },
  { gloss: "same", surfaces: ["same", "similar"], pos: "adjective" },
  { gloss: "different", surfaces: ["different"], pos: "adjective" },
  { gloss: "expensive", surfaces: ["expensive", "costly"], pos: "adjective" },
  { gloss: "cheap", surfaces: ["cheap", "inexpensive"], pos: "adjective" },
  { gloss: "more", surfaces: ["more"], pos: "quantifier" },
  { gloss: "less", surfaces: ["less", "fewer"], pos: "quantifier" },
  { gloss: "all", surfaces: ["all", "everything"], pos: "quantifier" },
  { gloss: "some", surfaces: ["some", "few"], pos: "quantifier" },
  { gloss: "many", surfaces: ["many", "lots", "a lot"], pos: "quantifier" },
  { gloss: "one", surfaces: ["one", "1"], pos: "number" },
  { gloss: "two", surfaces: ["two", "2"], pos: "number" },
  { gloss: "three", surfaces: ["three", "3"], pos: "number" },
  { gloss: "four", surfaces: ["four", "4"], pos: "number" },
  { gloss: "five", surfaces: ["five", "5"], pos: "number" },
  { gloss: "six", surfaces: ["six", "6"], pos: "number" },
  { gloss: "seven", surfaces: ["seven", "7"], pos: "number" },
  { gloss: "eight", surfaces: ["eight", "8"], pos: "number" },
  { gloss: "nine", surfaces: ["nine", "9"], pos: "number" },
  { gloss: "ten", surfaces: ["ten", "10"], pos: "number" },
  { gloss: "twenty", surfaces: ["twenty", "20"], pos: "number" },
  { gloss: "thirty", surfaces: ["thirty", "30"], pos: "number" },
  { gloss: "fifty", surfaces: ["fifty", "50"], pos: "number" },
  { gloss: "hundred", surfaces: ["hundred", "100"], pos: "number" },
  { gloss: "thousand", surfaces: ["thousand", "1000"], pos: "number" },
];

export const POS_BY_GLOSS: Record<string, PartOfSpeech> = Object.fromEntries(
  VOCABULARY.map((entry) => [entry.gloss, entry.pos]),
);

export const ENGLISH_BY_GLOSS: Record<string, string> = Object.fromEntries(
  VOCABULARY.map((entry) => [entry.gloss, entry.surfaces[0]]),
);

/**
 * English surface form -> gloss, longest first.
 *
 * Order matters: "how are you" has to be tried before "how", or the greeting is
 * lost and the sentence becomes a question about nothing. Callers walk this list
 * in order and take the first phrase that matches at the current position.
 */
export const SURFACE_FORMS: { surface: string; words: string[]; gloss: string }[] =
  VOCABULARY.flatMap((entry) =>
    entry.surfaces.map((surface) => ({
      surface,
      words: surface.split(" "),
      gloss: entry.gloss,
    })),
  ).sort((a, b) => b.words.length - a.words.length);
